name: Release 3X-UI for Docker

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout代码
        uses: actions/checkout@v4
      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3
      - name: 设置Buildx
        uses: docker/setup-buildx-action@v3
      - name: 登录GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: 设置Buildx多平台
  uses: docker/setup-buildx-action@v3
  with:
    platforms: linux/amd64,linux/arm64
    
      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/my-image:${{ github.sha }}
